run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs:
    - vendor

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - exportloopref
    - gocyclo
    - dupl
    - misspell
    - unparam
    - unconvert
    - gocritic
    - gofumpt
    - revive
  disable:
    - structcheck  # deprecated
    - varcheck     # deprecated
    - deadcode     # deprecated
    - golint       # deprecated
    - scopelint    # deprecated

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
